version: '3'

services:
  nest-db:
    container_name: nest-db
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    networks:
      - base_network
    volumes:
      - ./data/pg:/data/postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres

  nest-api:
    container_name: nest-api
    image: node:lts
    networks:
      - base_network
    ports:
      - 3333:3333
    command: sh -c "yarn start:dev"
    depends_on:
      - nest-db
    working_dir: /app
    volumes:
      - .:/app
    env_file: .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@nest-db:5432/${POSTGRES_DB}?schema=public

networks:
  base_network:


volumes:
  db-data:
